kind: Endpoints
apiVersion: v1
metadata:
  name: service-redis
  namespace: default
subsets:
  - addresses:
      - ip: 10.0.0.200
    ports:
      - name: redis
        port: 6379
        protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: service-redis
  namespace: default
spec:
  type: ClusterIP
  ports:
    - name: redis
      port: 6379
      protocol: TCP
      targetPort: 6379


