kind: Service
apiVersion: v1
metadata:
  name: service-clusterip-externalip
spec:
  type: ClusterIP
  selector:
    app: myweb
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  externalIPs:
  - 10.0.0.66
