apiVersion: v1
kind: Pod
metadata:
  name: pod-hostpath-test
spec:
  volumes:
  - name: timezone
    hostPath:
      #path: /etc/timezone
      path: /etc/localtime
      type: File
  containers:
  - name: c01
    image: wangxiaochun/nginx:1.20.0
    command: ["sh","-c","sleep 3600"]
  - name: c02
    image: wangxiaochun/nginx:1.20.0
    command: ["sh","-c","sleep 3600"]
    volumeMounts:
    - name: timezone
      mountPath: /etc/localtime
