apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-demo-3
  namespace: default
spec:
  accessModes: ["ReadWriteOnce"]
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
    limits:
      storage: 10Gi
