apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv001
spec:
  nfs:
    path: /nfs-data/v1
    server: 10.0.0.101
  accessModes: ["ReadWriteOnce"]
  capacity:
    storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv002
spec:
  nfs:
    path: /nfs-data/v2
    server: 10.0.0.101
  accessModes: ["ReadWriteOnce"]
  capacity:
    storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv003
spec:
  nfs:
    path: /nfs-data/v3
    server: 10.0.0.101
  accessModes: ["ReadWriteOnce"]
  capacity:
    storage: 2Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv004
spec:
  nfs:
    path: /nfs-data/v4
    server: 10.0.0.101
  accessModes: ["ReadWriteOnce"]
  capacity:
    storage: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: statefulset-headless
spec:
  ports: 
  - port: 80
  clusterIP: None
  selector:
    app: myapp-pod
