apiVersion: v1
kind: Secret
metadata:
 name: secret-test
type: kubernetes.io/basic-auth
data:
 username: YWRtaW4=
 password: cGFzc3dvcmQ=
 
---

apiVersion: v1
kind: Pod
metadata:
  name: pod-secret-volume
spec:
  volumes:
  - name: secret
    secret:
     secretName: secret-test
  containers:
    - name: secret-test-container
      image: wangxiaochun/nginx:1.20.0
      volumeMounts:
       - name: secret
         mountPath: /secret/
         readOnly: true
