apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-nginx-pvc
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-pvc
  template:
    metadata:
      labels:
        app: nginx-pvc
    spec:
      volumes:
      - name: volume-nginx
        persistentVolumeClaim:
          claimName: pvc-test
      containers:
      - name: nginx-pvc
        image: wangxiaochun/nginx:1.20.0
        volumeMounts:
        - name: volume-nginx
          mountPath: "/usr/share/nginx/html"

---
apiVersion: v1
kind: Service
metadata:
  name: service-nginx-pvc
spec:
  ports:
  - name: 80-80
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx-pvc
  type: LoadBalancer
